### PR TITLE
Adding login functionality.

### PR DESCRIPTION
**Pull request by brianropper**
The login functionality is complete.  One noticeable change is that Login.java is no longer the main entry point into the web application index.java is.  This is because on index.jsp I needed to change the action on the form to "/login".  Incorrect login attempts redirect you back to index.jsp and correct login attempts forward you to account.jsp where I have displayed the users information.  Where you get redirected to and how the data is displayed can, and in account.jsp's case, should be changed.

### CODE REVIEW

**Comment by komcrad** [comment]
The idea is that the Signup page is found at "/". So whether you want to delete index.java and change the mapping of Login.java to "/", or if you want to paste all your code into index.java and delete Signup.java, it's up to you. But I'm really happy that we can use el to pull data straight out of the User object. Also we need error messages to say that the login was unsuccessful. But good job. Just make those small changes and update this.

**Comment by komcrad** [comment]
Actually. We'll merge this. We do need the error message for a failed login but you can add this independant of this PR. If you want to combine login and index to one servlet you can, you decide.

**Comment by brianropper** [comment]
I'll leave it then.

**Comment by ghost** [comment]
Thanks for getting it done when you said you would. Derrick and I will work
on our portion tomorrow.

**Pull request merged**
